#! /bin/sh

sxhkd &
picom &

exec /home/pix/.config/polybar/launch.sh &

nm-applet &

feh --bg-scale "/home/pix/wallpaper.jpg"

#exec /home/pix/Documents/git/feh-blur-wallpaper/feh-blur &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config active_border_color  "#994875"
bspc config focused_border_color "#994876"

bspc config window_gap          12

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Spotify Premium" desktop='^5'
bspc rule -a "Firefox Nightly" desktop='^2'
bspc rule -a Steam desktop='^4'
bspc rule -a "Character Map" state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord-canary desktop='^3'

