#! /bin/sh

sxhkd &
picom &

exec /home/pix/.config/polybar/launch.sh &

nm-applet &

feh --bg-scale "/home/pix/wallpaper.jpg"

exec /home/pix/Documents/git/feh-blur-wallpaper/feh-blur &

#bspc monitor HDMI-1 -d I II III IV V
bspc monitor DVI-D-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config active_border_color  "#994875"
bspc config focused_border_color "#994876"
bspc config normal_border_color  "#00000000"

bspc config window_gap          12

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Spotify desktop='^5'
bspc rule -a Nightly desktop='^2'
bspc rule -a Steam desktop='^4'
bspc rule -a Screenshot state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^3'

MON_ID=$(bspc query -M -m "$1")
MON_POS="$2"

[ $(bspc query -M -m "$MON_POS") != "$MON_ID" ] && bspc monitor "$MON_POS" -s "$MON_ID"

bspc subscribe monitor_swap | while read msg ; do
	[ $(bspc query -M -m "$MON_POS") != "$MON_ID" ] && bspc monitor "$MON_POS" -s "$MON_ID"
done

enforce_monitor_position HDMI-1 '^1' &
